version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"

  auth-service:
    build: ../../services/auth-service
    ports:
      - "5001:5001"
    depends_on:
      - mongo

  doctor-service:
    build: ../../services/doctor-service
    ports:
      - "5003:5003"
    depends_on:
      - mongo

  appointment-service:
    build: ../../services/appointment-service
    ports:
      - "5004:5004"
    depends_on:
      - mongo

  frontend:
    build: ../../frontend
    ports:
      - "3000:3000"

  patient-service:
    build: ../../services/patient-service
    container_name: patient-service
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
      - MONGODB_URI=mongodb://mongo:27017/smart_healthcare
      - JWT_SECRET=${JWT_SECRET}
      - FILE_UPLOAD_PATH=./uploads
      - MAX_FILE_SIZE=5242880
    depends_on:
      - mongo
    volumes:
      - ../../services/patient-service:/app
      - /app/node_modules
      - patient_uploads:/app/uploads

volumes:
  patient_uploads: