version: "3.8"

services:
  # mongo:
  #   image: mongo
  #   container_name: mongo
  #   ports:
  #     - "27017:27017"

  auth-service:
    build: ../../services/auth-service
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - MONGO_URI=${AUTH_MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - INTERNAL_SERVICE_API_KEY=${INTERNAL_SERVICE_API_KEY}
    # depends_on:
    #   - mongo

  doctor-service:
    build: ../../services/doctor-service
    ports:
      - "5003:5003"
    environment:
      - PORT=5003
      - MONGO_URI=${DOCTOR_MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - APPOINTMENT_SERVICE_URL=http://appointment-service:5004
      - NOTIFICATION_SERVICE_URL=http://notification-service:5010
      - INTERNAL_SERVICE_API_KEY=${INTERNAL_SERVICE_API_KEY}
    # depends_on:
    #   - mongo

  appointment-service:
    build: ../../services/appointment-service
    ports:
      - "5004:5004"
    environment:
      - PORT=5004
      - MONGO_URI=${APPOINTMENT_MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - INTERNAL_SERVICE_API_KEY=${INTERNAL_SERVICE_API_KEY}
      - DOCTOR_SERVICE_URL=http://doctor-service:5003/api/doctor
    # depends_on:
    #   - mongo

  patient-service:
    build: ../../services/patient-service
    container_name: patient-service
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
      - MONGO_URI=${PATIENT_MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - FILE_UPLOAD_PATH=./uploads
      - MAX_FILE_SIZE=5242880
    # depends_on:
    #   - mongo
    volumes:
      - ../../services/patient-service:/app
      - /app/node_modules
      - patient_uploads:/app/uploads

  notification-service:
    build: ../../services/notification-service
    ports:
      - "5011:5010"
    environment:
      - PORT=5010
      - MONGO_URI=${NOTIFICATION_MONGO_URI}
      - AUTH_SERVICE_URL=http://auth-service:5001
      - INTERNAL_SERVICE_API_KEY=${INTERNAL_SERVICE_API_KEY}
    depends_on:
      # - mongo
      - auth-service

  frontend:
    build: ../../frontend
    ports:
      - "3000:5173"
    environment:
      - VITE_AUTH_BASE_URL=${VITE_AUTH_BASE_URL}
      - VITE_PATIENT_BASE_URL=${VITE_PATIENT_BASE_URL}
      - VITE_DOCTOR_BASE_URL=${VITE_DOCTOR_BASE_URL}
      - VITE_APPOINTMENT_BASE_URL=${VITE_APPOINTMENT_BASE_URL}


volumes:
  patient_uploads: