apiVersion: v1
kind: Service
metadata:
  name: ai-feature-service
spec:
  selector:
    app: ai-feature-service
  ports:
    - protocol: TCP
      port: 5020
      targetPort: 5020
      nodePort: 30020
  type: NodePort